"""Probe the upstream provider and record which models are *actually* runnable.

The provider's catalog has no reliable field marking a model as serverless /
instantly available (per-token pricing over-predicts — most priced models still
return "non-serverless"). The only trustworthy signal is a real call. This script
sends a tiny (1-token) chat to every text model and writes the IDs that succeed
to ``app/serverless_models.py`` (the ``RUNNABLE`` list), which the Cloud Models
catalog uses to set the "ready to run" flag.

    python -m scripts.refresh_serverless

Re-run periodically (the serverless set changes as the provider adds/removes
models).
"""
from __future__ import annotations

import asyncio
from pathlib import Path

import httpx

from app.config import settings

TEXT_TYPES = {"chat", "language", "code"}
OUT = Path(__file__).resolve().parent.parent / "app" / "serverless_models.py"

_HEADER = '''"""Verified runnable cloud models (the "ready to run" allowlist).

Auto-generated by ``scripts/refresh_serverless.py`` — it probes every text model
upstream and records the IDs that actually respond. The provider catalog has no
reliable serverless flag, so this probed list is the source of truth for the
Cloud Models page. Stored as Python (not JSON) so it ships in the Modal image
with the rest of the ``app`` package. Re-run the script to refresh.
"""

RUNNABLE = [
'''


async def _probe(client: httpx.AsyncClient, mid: str, sem: asyncio.Semaphore) -> tuple[str, bool]:
    async with sem:
        try:
            r = await client.post(
                f"{settings.together_base_url}/chat/completions",
                headers={"Authorization": f"Bearer {settings.together_api_key}"},
                json={"model": mid, "messages": [{"role": "user", "content": "hi"}], "max_tokens": 1},
                timeout=60,
            )
            return mid, r.status_code == 200
        except Exception:  # noqa: BLE001
            return mid, False


async def main() -> None:
    key = settings.together_api_key
    if not key:
        raise SystemExit("TOGETHER_API_KEY not set")

    async with httpx.AsyncClient() as client:
        cat = (await client.get(
            f"{settings.together_base_url}/models",
            headers={"Authorization": f"Bearer {key}"},
            timeout=30,
        )).json()
        items = cat if isinstance(cat, list) else cat.get("data", [])
        candidates = [m["id"] for m in items if (m.get("type") or "").lower() in TEXT_TYPES]
        print(f"Probing {len(candidates)} text models…")

        sem = asyncio.Semaphore(8)
        results = await asyncio.gather(*[_probe(client, mid, sem) for mid in candidates])

    working = sorted(mid for mid, ok in results if ok)
    body = _HEADER + "".join(f"    {mid!r},\n" for mid in working) + "]\n"
    OUT.write_text(body)
    print(f"{len(working)} runnable models -> {OUT}")


if __name__ == "__main__":
    asyncio.run(main())
