"""Verified runnable cloud models (the "ready to run" allowlist).

Auto-generated by ``scripts/refresh_serverless.py`` — it probes every text model
upstream and records the IDs that actually respond. The provider catalog has no
reliable serverless flag, so this probed list is the source of truth for the
Cloud Models page. Stored as Python (not JSON) so it ships in the Modal image
with the rest of the ``app`` package. Re-run the script to refresh.
"""

RUNNABLE = [
    'LiquidAI/LFM2-24B-A2B',
    'MiniMaxAI/MiniMax-M2.7',
    'MiniMaxAI/MiniMax-M3',
    'Qwen/Qwen2.5-7B-Instruct-Turbo',
    'Qwen/Qwen3-235B-A22B-Instruct-2507-FP8',
    'Qwen/Qwen3-235B-A22B-Instruct-2507-tput',
    'Qwen/Qwen3.5-397B-A17B',
    'Qwen/Qwen3.5-9B',
    'arize-ai/qwen-2-1.5b-instruct',
    'deepcogito/cogito-v2-1-671b',
    'deepseek-ai/DeepSeek-V4-Pro',
    'essentialai/rnj-1-instruct',
    'google/gemma-3n-E4B-it',
    'google/gemma-4-31B-it',
    'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    'meta-llama/Meta-Llama-3-8B-Instruct-Lite',
    'moonshotai/Kimi-K2.6',
    'moonshotai/Kimi-K2.7-Code',
    'nvidia/nemotron-3-ultra-550b-a55b',
    'openai/gpt-oss-120b',
    'openai/gpt-oss-20b',
    'pearl-ai/gemma-4-31b-it',
    'zai-org/GLM-5',
    'zai-org/GLM-5.1',
    'zai-org/GLM-5.2',
]
